### ISSUE TITLE
Conflicts with plugins that cancel BlockBreakEvent

### ISSUE THREAD

**Issue by lucyydotp** [byteful/LevelTools#11]
LevelTools handles BlockBreakEvent before other plugins such as claiming plugins have a chance to alter or cancel events if necessary. This means that tools still gain XP without taking any durability or moving any blocks, should the event be cancelled.

**Comment by byteful** [comment]
What version of LevelTools are you on? I fixed a bug like this with a conflict with WorldGuard.
