### ISSUE TITLE
Repaired item lose its level when repaired with another tools, and the lore will be gone temporarily

### ISSUE THREAD

**Issue by noiverre** [byteful/LevelTools#12]
Method 1
1. Get any levellable item to level 2
2. Get one other item of the same type to level 1
3. Repair both of them using anvil, place the level 2 or level 1 item in the first slot and the latter in the second slot
4. End result item will lose any of their levels

Method 2
1. Get any levellable item to level 2
2. Get one other item of the same type to level 1
3. Repair both of them using vanilla crafting slot
4. End result item will lose any of their levels

When repaired using minerals such as diamond, the end result item will lose their lore but their level will be maintained and re-added into the item lore after gaining experience

Expected behavior:
1. Either the highest level or the first slot of anvil should keep their level when repaired

Version:
Paper 1.18.1 build 101
Latest version of LevelTools

**Comment by byteful** [comment]
Thank you for the detailed bug report. I really appreciate this. I'll look into this ASAP.

**Comment by byteful** [comment]
Fixed bug with recent PR #13
