### ISSUE TITLE
[Bug] io.netty.handler.codec.EncoderException: String too big (was 284667 bytes encoded, max 262144)

### ISSUE THREAD

**Issue by noiverre** [byteful/LevelTools#15]
Method:
1. Create any level rewards in any tool
2. Give 32767 enchantments to them
3. Get the specified tool to the level
4. Hover over the item
5. Client crashes

Configuration:
https://paste.gg/p/anonymous/39b2e4ec4953434f973dc00257d05b5c

Errors:
![image](https://user-images.githubusercontent.com/77881970/148870598-13a7a76d-d16f-46d9-932e-a8a4fb5b6d07.png)
https://paste.gg/p/anonymous/9f36ae06a22c4a11bc4c42309c7503f1

Plugins:
1. ProtocolLib
2. ViaVersion + ViaBackwards 4.1.1
3. Protocolize (on Waterfall)

Version:
1. Latest version of LevelTools
2. Latest build of Pufferfish https://github.com/pufferfish-gg/Pufferfish
3. Pterodactyl yolks java 17

**Comment by byteful** [comment]
Does this happen with normal Spigot 1.18.1?

**Comment by noiverre** [comment]
I didn't check with spigot, but perhaps it has something to do with the proxy?

**Comment by byteful** [comment]
I doubt it's the proxy since this error is on the Spigot server end.

**Comment by byteful** [comment]
Have you checked with the default Spigot JAR to see if this still happens?
