### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by masmc05** [byteful/LevelTools#35]
![image-3](https://user-images.githubusercontent.com/63639746/212552566-0a5157fe-56e9-4446-ba94-8b230e504295.png)
too many jdbc connections have your plugin as their root

**Comment by masmc05** [comment]
3 gb of connections

**Comment by byteful** [comment]
huh, alright I'll take a look at this as soon as I can

**Comment by masmc05** [comment]
> huh, alright I'll take a look at this as soon as I can

is there any progress in this? we still have our server crashed if we delay the restart event by a bit

**Comment by byteful** [comment]
> > huh, alright I'll take a look at this as soon as I can
> 
> is there any progress in this? we still have our server crashed if we delay the restart event by a bit

Have you been reloading your plugin anytime during this issue?

**Comment by masmc05** [comment]
no
