### ISSUE TITLE
I've been using this plugin for a while now and it's feeling very good. I make the following suggestions and fixes, I hope you can consider my suggestion

### ISSUE THREAD

**Issue by Cqmmls** [byteful/LevelTools#43]
1.display in config:
  name:
    enabled: true
    text: "{item} &7- &b{level}"
{item} will disappear, e.g. "Iron Sword - 1" as I guess will become "- 1", meaning the item name disappears

2.When the player uses the command /leveltools level or /leveltools levelup to upgrade a weapon or tool, the sound will look like in config when the upgrade is not upgraded  
# Configuration for the sound played during a level up.
level_up_sound:
  sound: "ENTITY_PLAYER_LEVELUP"
  pitch: 1.0
  volume: 10.0
It doesn't have any effect, but I think it's better if you could consider adding sound effects

**Comment by byteful** [comment]
Sorry, I don't plan to add new features to LevelTools right now.
