### ISSUE TITLE
Block break events that are cancelled still give XP

### ISSUE THREAD

**Issue by bristermitten** [byteful/LevelTools#7]
For example breaking blocks under worldguard protection

Perhaps also make the plugin only give xp for blocks, not things like flowers and grass

**Comment by byteful** [comment]
You can blacklist certain blocks like flowers and grass. I'd like to keep support for flexibility, but I can provide you a config that I used on 1.17 that blacklists these blocks.

**Comment by byteful** [comment]
Fixed with new pull request. Version release coming in a few.
